FROM python:3.8

WORKDIR /app

ENV REDIS_HOST=redis
ENV DYNAMO_HOST=dynamodb
ENV IS_OFFLINE=true
ENV SERVICE_MONITOR_TABLE=monitors
ENV AWS_ACCESS_KEY_ID=dummy
ENV AWS_SECRET_ACCESS_KEY=dummy
ENV AWS_SESSION_TOKEN=dummy

CMD ["make"]