tests:
  build: .
  stop_signal: SIGKILL
  dockerfile: Dockerfile
  tty: true
  working_dir: $PWD
  volumes:
    - $PWD:$PWD
  links:
    - redis
  command: ["make", "init", "ci", "coverage"]
redis:
  image: redis