tests:
  build: .
  stop_signal: SIGKILL
  dockerfile: Dockerfile
  tty: true
  working_dir: $PWD
  volumes:
    - $PWD:$PWD
  links:
    - redis
    - dynamodb
  command: ["make", "init", "ci", "coverage"]
redis:
  image: redis
dynamodb:
  image: amazon/dynamodb-local:latest
  command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]