name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: "Docker Build"
        run: docker-compose --log-level INFO up --abort-on-container-exit --exit-code-from tests --build

      - name: "Docker Logs"
        run: docker-compose logs

      - name: "Publish code coverage"
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml